name: chem-spectra-app
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - qhull
  - freetype
  - hdf5
  - netcdf4
  - atomicwrites
  - attrs
  - certifi
  - chardet
  - Click
  - coverage
  - cycler
  - entrypoints
  - flake8
  - flask
  - gunicorn
  - idna
  - importlib
  - itsdangerous
  - Jinja2
  - MarkupSafe
  - matplotlib
  - mccabe
  - numpy
  - olefile
  - pandas
  - pathlib2
  - Pillow
  - pluggy
  - py
  - pycodestyle
  - pyflakes
  - pymzml
  - pyparsing
  - pytest
  - python
  - pytz
  - regex
  - requests
  - scipy
  - six
  - urllib3
  - Werkzeug
  - zipp
  - pyopenms
  - pip
  - pip:
    -e git+https://github.com/ComPlat/nmrglue.git@c5a7d4d0073fedff68808b4e9c95836a8c20413e#egg=nmrglue
